name: CI
on: [push, pull_request]

jobs:
    build:
      name: Run Script
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Script
          run: |
           powershell test.ps1
          
          shell: pwsh
          
