name: Multiline
on: push

jobs:
    build:
      name: Run Script
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v1
        - name: Script
          shell: pwsh
          run: |
            Write-Host "Line 1"
            Write-Host "Line 2"
            Write-Host "Line 3"
          
