name: CI
on: [push, pull_request]
jobs:
    job1:
      name: Run Script
      runs-on: self-hosted
      if: env=dev
      environment: dev
      steps: 
        - uses: actions/checkout@v1
        - name: Script
          run: |
           ./test.ps1
